<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<meta charset="UTF-8">
<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo/marie.png'))
        ->prependStylesheet($this->basePath('customer/date/css/style.css'))
        ->prependStylesheet($this->basePath('customer/date/css/bootstrap-select'))
        ->prependStylesheet($this->basePath('customer/date/css/bootstrap-select.min.css'))
        ->prependStylesheet($this->basePath('customer/date/css/jquery.datetimepicker.css'))
        ->prependStylesheet('http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css')
?>

<!-- Scripts -->
<?php
echo $this->headScript()
        ->prependFile($this->basePath('customer/date/js/jquery.datetimepicker.full.min.js'))
        ->prependFile($this->basePath('customer/date/js/jquery.datetimepicker.full.js'))
        ->prependFile($this->basePath('customer/date/js/jquery.datetimepicker.js'))
        ->prependFile($this->basePath('customer/date/js/jquery.datetimepicker.min.js'))
        ->prependFile($this->basePath('customer/date/js/bootstrap-select.js'))
;
?>
<div class="container">
    <div>
        <form class="form-horizontal col-lg-12" method="POST" enctype="multipart/form-data" style="border: 2px solid #CBE6F4;background-color: white">
            <br/>
            <h1 class="text-center text-primary" style="font-family: serif; font-size: 14px; font-weight: bold">Ajouter un nouveau produit </h1>
            <div class="form-group">
                <div class="col-sm-8">
                    <input type="text" name="code" class="form-control" id="nom" value="" title="code" placeholder="code ou série du produit" required="true">
                </div>
            </div>
            <div class="form-group">                
                <div class="col-sm-8">
                    <select class="form-control col-sm-8" id="categorie" name="categorie" title="Catégorie du produit">
                        <option value="" style="color: deepskyblue">-- Sélectionner la catégorie du produit --</option>
                        <?php
                        foreach ($categories as $categorie) {
                            echo '<option value="' . $categorie->getId() . '" style="color: deepskyblue"> &nbsp;' . $categorie->getNom() .' </option>';
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-8">
                    <input type="text" name="nom" class="form-control" id="nom" value="" title="Nom" placeholder="nom du produit" required="true">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-8">
                    <select class="form-control col-sm-8" id="marque" name="marque" title="marque">
                        <option value="" style="color: deepskyblue">-- Sélectionner la marque --</option>
                        <option value="Masculin" style="color: deepskyblue">&nbsp;Samsung</option>
                        <option value="Féminin" style="color: deepskyblue">&nbsp;Techno</option>
                        <option value="Féminin" style="color: deepskyblue">&nbsp;LG</option>
                        <option value="Féminin" style="color: deepskyblue">&nbsp;HTC</option>
                        <option value="Féminin" style="color: deepskyblue">&nbsp;VMC</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class='input-group date col-sm-8' >
                    <input type='date' class="form-control"  id='dateEnregistrement' name="dateEnregistrement" value="" placeholder="Date d'enregistrement" style="margin-left: 3px" title="Date d'enregistrement"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <div class='input-group date col-sm-8' >
                    <input type='date' class="form-control"  id='dateFabrication' name="dateFabrication" value="" placeholder="Date de fabrication" style="margin-left: 3px" title="Date d'enregistrement"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <div class='input-group date col-sm-8' >
                    <input type='date' class="form-control"  id='datePeremption' name="datePeremption" value="" placeholder="Date de péremption" style="margin-left: 3px" title="Date d'enregistrement"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-8">
                    <input type="number"  class="form-control" id="prixAchat" name="prixAchat" placeholder="Prix d'achat(FCFA)" value="" title="Prénom">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-8">
                    <input type="number"  class="form-control" id="prixAchat" name="prixVente" placeholder="Prix de vente(FCFA)" value="" title="Prénom">
                </div>
            </div>
            <div class=" form-group">
                <div class="col-sm-8">
                    <input type="file" name="images[]" multiple>
                </div>
            </div>
            <div class="form-group">                    
                <div class="row col-sm-offset-2">
                    <hr>
                    <div class="col-sm-2">
                        <button type="submit" name="submit" class="btn btn-primary "><span class="glyphicon col-lg-12
                                                                                           glyphicon-ok-sign"></span>Enregistrer</button>
                        <br>
                        <br>
                    </div>
                    <div class="col-sm-2">
                        <button type="reset" name="cancel" class="btn btn-warning "><span class="glyphicon col-lg-12
                                                                                          glyphicon-asterisk"></span>Annuler</button>
                        <br>
                        <br>
                    </div>
                </div>
        </form>
    </div>
    <script>
        $('.selectpicker').selectpicker();
    </script>
    <script type="text/javascript">
        $(function() {
            $('#dateDeNaissance').datetimepicker({
                locale: 'ru',
                lang: 'en',
                //timepicker: false,
                format: 'd-m-Y',
                //formatDate: 'Y/m/d',
                // minDate: '-1970/01/02', // yesterday is minimum date
                //maxDate: '+1970/01/02' // and tommorow is maximum date calendar
            });
            $('#stPatron').datetimepicker({
                locale: 'ru',
                lang: 'en',
                //timepicker: false,
                format: 'd-m-Y',
                //formatDate: 'Y/m/d',
                // minDate: '-1970/01/02', // yesterday is minimum date
                //maxDate: '+1970/01/02' // and tommorow is maximum date calendar
            });
            $('#dateAdmission').datetimepicker({
                locale: 'ru',
                lang: 'en',
                //timepicker: false,
                format: 'd-m-Y',
                //formatDate: 'Y/m/d',
                // minDate: '-1970/01/02', // yesterday is minimum date
                //maxDate: '+1970/01/02' // and tommorow is maximum date calendar
            });
        });
    </script>
</div>

