<div>
    <div>
        <form class="form-horizontal col-lg-12" method="POST" enctype="multipart/form-data" style="border: 2px solid #CBE6F4;background-color: white">
            <br/>
            <p class="text-center text-primary" style="font-family: serif; font-size: 14px; font-weight: bold">Informations personnel </p>
            <hr>
            <div class="form-group">
                <label for="login" class="col-sm-3 control-label">Login :</label>
                <div class="col-sm-8">
                    <input type="text"  class="form-control"  name="login" id="login" placeholder="Ancien login">
                </div>
            </div>
            <div class="form-group">
                <label for="oldpassword" class="col-sm-3 control-label">Ancien mot de passe :</label>
                <div class="col-sm-8">
                    <input type="password"  class="form-control"  name="oldpassword" id="oldpassword" placeholder="Ancien mot de passe">
                </div>
            </div>
            <div class="form-group">
                <label for="newpassword" class="col-sm-3 control-label">Nouveau mot de passe :</label>
                <div class="col-sm-8">
                    <input type="password"  class="form-control"  name="newpassword" id="newpassword" placeholder="Nouveau mot de passe">
                </div>
            </div>
            <div class="form-group">
                <label for="confirmpassword" class="col-sm-3 control-label">Confirmation:</label>
                <div class="col-sm-8">
                    <input type="password"  class="form-control"  name="confirmpassword" id="confirmpassword" placeholder="Confirmation">
                </div>
            </div>
            <br>
            <div class="row col-sm-offset-2">
                <div class="col-sm-2">
                    <button type="submit" name="submit" class="btn btn-default "><span class="glyphicon glyphicon-ok-sign"></span>Modifier</button>
                    <br>
                    <br>
                </div>
                <div class="col-sm-2" style="margin-left: 20px">
                    <button type="cancel" name="cancel" class="btn btn-default " >Annuler</button>
                    <br>
                    <br>
                </div>
            </div>
        </form>
    </div>
</div>

