<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<div class="main-nav navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">
                <h1><img class="img-responsive col-sm-1 col-xs-1 col-lg-1" src="img/logo/logo.png" alt="logo"></h1>
            </a>                    
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">                 
                <li class="scroll active"><a href="#home">Accueil</a></li>
                <li class="scroll"><a href="#services">About</a></li> 
                <li class="scroll"><a href="#about-us">Produits</a></li>                     
                <li class="scroll"><a href="#portfolio">Services</a></li>
                <li class="scroll"><a href="#team">R&eacute;alisations</a></li>
                <li class="scroll"><a href="#blog">Contact</a></li>                        
            </ul>
        </div>
    </div>
</div>
